---
- hosts: 192.168.0.113
  gather_facts: no
  become: true
  
  tasks:
    - name: create directory to generate and store reports
      file:
        path: /opt/report
        state: directory

    - name: create a report data
      command: ansible all -m setup  -t /opt/report

    - name: generate report
      shell: /home/rdodia/ansible-cmdb-1.30/ansible-cmdb /out/report > /opt/report/system-overview.$(date +%Y%m%d%H%M%S).html
