---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: create directory to generate and store reports
      file:
        path: report
        state: directory

    - name: create a report data
      shell: ansible -m setup -t report localhost

    - name: generate report
      shell: /usr/local/bin/ansible-cmdb report > report/system-overview.html
