---
- hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
    - name: create directory to generate and store reports
      file:
        path: report
        state: directory

    - name: create a report data
      command: ansible -m setup -t report localhost

    - name: generate report
      shell: /usr/local/bin/ansible-cmdb report > /opt/report/system-overview.$(date +%Y%m%d%H%M%S).html
