---
- hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
    - name: create directory to generate and store reports
      file:
        path: report
        state: directory

    - name: create a report data
      command: ansible localhost -m setup  -t report

    - name: generate report
      command: ansible-cmdb report > report/systemoverview.html
