---
- hosts: all
  gather_facts: no
  become: true
  vars:
   ansible_become_password: x

  tasks:
    - name: create directory to generate and store reports
      file:
        path: /opt/report2
        state: directory
      delegate_to: 192.168.0.104

    - name: create a report data
      shell: sudo ansible -m setup -t /out/report2 localhost

    - name: generate report
      shell: ansible-cmdb /out/report2 > /opt/report2/system-overview.$(date +%Y%m%d%H%M%S).html
